const countryFlags: Record<string, string> = {
  Australia: '🇦🇺',
  Brazil: '🇧🇷',
  Canada: '🇨🇦',
  China: '🇨🇳',
  'European Union': '🇪🇺',
  Finland: '🇫🇮',
  France: '🇫🇷',
  'Hong Kong': '🇭🇰',
  'Hong Kong SAR': '🇭🇰',
  Iceland: '🇮🇸',
  India: '🇮🇳',
  Indonesia: '🇮🇩',
  Japan: '🇯🇵',
  Liechtenstein: '🇱🇮',
  Lithuania: '🇱🇹',
  Malta: '🇲🇹',
  Mexico: '🇲🇽',
  Netherlands: '🇳🇱',
  Nigeria: '🇳🇬',
  Russia: '🇷🇺',
  Singapore: '🇸🇬',
  'South Africa': '🇿🇦',
  'South Korea': '🇰🇷',
  Switzerland: '🇨🇭',
  Turkey: '🇹🇷',
  'United Arab Emirates': '🇦🇪',
  'United Kingdom': '🇬🇧',
  Global: '🌍',
  Argentina: '🇦🇷',
  'Costa Rica': '🇨🇷',
  Colombia: '🇨🇴',
  Bolivia: '🇧🇴',
  Peru: '🇵🇪',
  'El Salvador': '🇸🇻',
  Thailand: '🇹🇭',
  Malaysia: '🇲🇾',
  Cambodia: '🇰🇭',
  Vietnam: '🇻🇳',
  Philippines: '🇵🇭',
  Laos: '🇱🇦',
  'Saudi Arabia': '🇸🇦',
  Bahrain: '🇧🇭',
  Qatar: '🇶🇦',
  Israel: '🇮🇱',
  Egypt: '🇪🇬',
  Kenya: '🇰🇪',
  Ghana: '🇬🇭',
  Tanzania: '🇹🇿',
  Ethiopia: '🇪🇹',
  Rwanda: '🇷🇼',
  Zimbabwe: '🇿🇼',
  'New Zealand': '🇳🇿',
  Sweden: '🇸🇪',
  Poland: '🇵🇱',
  Spain: '🇪🇸',
  Portugal: '🇵🇹',
  Italy: '🇮🇹',
  Hungary: '🇭🇺',
  Germany: '🇩🇪',
  Belgium: '🇧🇪',
  Luxembourg: '🇱🇺',
  Norway: '🇳🇴',
  Denmark: '🇩🇰',
  Armenia: '🇦🇲',
  Georgia: '🇬🇪',
  Azerbaijan: '🇦🇿',
  Kazakhstan: '🇰🇿',
  Kyrgyzstan: '🇰🇬',
  Uzbekistan: '🇺🇿',
}

export function getCountryFlag(country?: string | null, explicitFlag?: string | null): string {
  if (explicitFlag) return explicitFlag
  if (!country) return '🏳️'
  return countryFlags[country] || '🏳️'
}
