/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Always returns 200 if the process is up. Use as a load-balancer health probe.
         */
        get: operations["AppController_health_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/production/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Monthly production facts
         * @description Returns paginated monthly production rows from `fact_production_monthly`.
         *
         *     Filters: `operator`, `formation`, `province`, `vm=true|false`, `from=YYYY-MM`, `to=YYYY-MM`.
         *
         *     Pass `group_by=operator|concession|formation|province` to aggregate rows on the fly — the response items follow the `GroupedProductionRowDto` shape (the group key field is named after the chosen `group_by`).
         */
        get: operations["ProductionController_monthly_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/production/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest-month summary
         * @description Single-row totals for the most recent month available, including BOE total, VM share of oil/gas/BOE, and the top 5 operators by BOE.
         */
        get: operations["ProductionController_latest_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List operators with latest-month totals
         * @description Returns one row per operator, joined to the latest month available in `agg_monthly_by_operator`. Includes BOE share from Vaca Muerta wells.
         */
        get: operations["OperatorsController_list_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operators/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Operator detail
         * @description Metadata, latest-month rank, latest-month totals and YTD totals for one operator.
         */
        get: operations["OperatorsController_detail_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operators/{slug}/production": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Monthly time series for an operator
         * @description One point per `date_month`. Optionally filtered with `from` / `to`.
         */
        get: operations["OperatorsController_production_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wells": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List wells
         * @description Paginated well catalog. Supports filters by operator/formation/basin/province/concession and a substring search on `sigla`.
         */
        get: operations["WellsController_list_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wells/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Well detail
         * @description Well metadata plus a `latest_production` block with the most recent monthly fact for this well.
         */
        get: operations["WellsController_detail_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wells/{id}/production": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Monthly production for a single well
         * @description Time-ordered monthly facts. Optionally filtered with `from` / `to`.
         */
        get: operations["WellsController_production_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geo/wells": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Wells as a GeoJSON FeatureCollection
         * @description Returns **raw GeoJSON** (no `data` / `meta` envelope) so the response can be fed directly into Mapbox / MapLibre / Leaflet.
         *
         *     Use `bbox=west,south,east,north` for viewport-based loading.
         *
         *     Wells without coordinates are excluded. The `limit` caps total features per request (max 1000).
         */
        get: operations["GeoController_wells_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geo/wells/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Single well as a GeoJSON Feature
         * @description Returns raw GeoJSON. 404 if the well has no recorded coordinates.
         */
        get: operations["GeoController_well_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data-freshness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Data freshness + row counts
         * @description Returns the earliest/latest months available plus a row count per table. Use this to attribute the data source on the frontend and to detect stale ingestion.
         */
        get: operations["DataStatusController_freshness_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/minerals/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List mining projects
         * @description Paginated, filterable catalog of mining projects across commodities (silver, gold, uranium, copper, lithium, …). Each list item includes a small `commodity_highlights` map derived from the project's resources JSONB.
         */
        get: operations["MineralsController_list_v2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/minerals/projects/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mining project detail
         * @description Full project fact sheet, including raw `resources` and `reserves` JSONB exactly as the pipeline emitted them.
         */
        get: operations["MineralsController_detail_v2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/minerals/commodities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Commodity rollups
         * @description Project counts and aggregate resource/reserve totals per commodity.
         */
        get: operations["MineralsController_commodities_v2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/minerals/commodities/{commodity}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Projects for one commodity
         * @description All projects whose primary commodity matches (case-insensitive), with their raw resources/reserves attached.
         */
        get: operations["MineralsController_commodityProjects_v2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/minerals/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Projects as a GeoJSON FeatureCollection
         * @description Raw GeoJSON (no `data` / `meta` envelope). Projects without coordinates are excluded.
         */
        get: operations["MineralsController_map_v2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/minerals/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard summary
         * @description Totals and breakdowns by commodity, status, and province, plus the set of source pipelines that fed the database.
         */
        get: operations["MineralsController_summary_v2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/minerals/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live commodity prices
         * @description Latest quotes for the tracked commodities (Silver, Gold, Copper, Uranium, Lithium). Uranium and Lithium use sector ETFs as proxies. Sourced from Yahoo Finance; 5-minute server-side cache.
         */
        get: operations["MineralsController_prices_v2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/minerals/prices/{commodity}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live commodity price (single)
         * @description Latest quote for one commodity. Case-insensitive name match against the supported set.
         */
        get: operations["MineralsController_price_v2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prices/commodities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest commodity prices
         * @description One row per tracked commodity series (gold, silver, copper, lithium_etf, uranium_etf) with the most recent monthly value. Sourced from Yahoo Finance (monthly snapshot fetched upstream).
         */
        get: operations["PricesController_commodities_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prices/commodities/{commodity}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Commodity time series
         * @description Monthly value history for one commodity (`gold`, `silver`, `copper`, `lithium_etf`, `uranium_etf`).
         */
        get: operations["PricesController_commoditySeries_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prices/energy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest energy prices (EIA)
         * @description Latest EIA-sourced energy series (Brent, WTI, Henry Hub). Returns an empty array when the EIA pipeline has not yet run — set `EIA_API_KEY` upstream and re-seed.
         */
        get: operations["PricesController_energy_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prices/fuel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gas station fuel prices
         * @description Filterable list of station-level fuel prices (current snapshot). Use `provincia`, `producto`, `bandera`, `from`, `to`.
         */
        get: operations["PricesController_fuel_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prices/fuel/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest fuel prices by province + product
         * @description For each (provincia, producto) pair, returns the latest fecha_vigencia plus min / avg / max across stations on that date. Optionally filter by `provincia` and / or `producto`.
         */
        get: operations["PricesController_fuelLatest_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/macro/fx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * USD/ARS time series
         * @description Daily official (BCRA) and blue (parallel) exchange rates from bluelytics. Both sell and buy sides. Range filterable.
         */
        get: operations["MacroController_fxSeries_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/macro/fx/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest USD/ARS rates
         * @description Latest oficial + blue (sell + buy) rates.
         */
        get: operations["MacroController_fxLatest_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rig-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Argentina rig-count time series
         * @description Monthly Baker Hughes rig count for Argentina (oil / gas / total). Currently a small placeholder dataset until the scraper stabilizes.
         */
        get: operations["MacroController_rigCount_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rig-count/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest rig-count snapshot
         * @description Most recent month's oil / gas / total rig count.
         */
        get: operations["MacroController_rigCountLatest_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthDto: {
            /** @example ok */
            status: string;
            /** @example petroldata-api */
            service: string;
        };
        GroupedProductionRowDto: {
            /** @example 2026-04-01 */
            date_month: string;
            /**
             * @description The group key. Field name varies with `group_by`: `operator`, `concession`, `formation`, or `province`.
             * @example ypf
             */
            operator: string;
            /** @example 1478788.97 */
            oil_m3: number;
            /** @example 9301301.71 */
            oil_bbl: number;
            /** @example 310043.31 */
            oil_bbl_d: number;
            /** @example 690500.26 */
            gas_thousand_m3: number;
            /** @example 23.01 */
            gas_mm3_d: number;
            /** @example 24384809.66 */
            gas_mcf: number;
            /** @example 812.82 */
            gas_mmcf_d: number;
            /** @example 34491371.36 */
            boe: number;
            /** @example 2465 */
            active_wells: number;
        };
        MetaDto: {
            /** @example Secretaría de Energía / datos.energia.gob.ar */
            source: string;
            /** @example Producción de petróleo y gas por pozo */
            dataset: string;
            /** @example CC-BY-4.0 */
            license: string;
            /** @example 2026-04-01 */
            last_source_update: Record<string, never> | null;
            /** @example 2026-05-27T14:30:00.000Z */
            last_ingested_at: string;
            /** @example formation + unconventional + sub-tipo */
            vaca_muerta_filter: string;
        };
        PaginationMetaDto: {
            /** @example 1 */
            page: number;
            /** @example 50 */
            limit: number;
            /** @example 1000 */
            total: number;
        };
        ProductionFactDto: {
            /** @example 1 */
            id: number;
            /** @example 2026-04-01 */
            date_month: string;
            /** @example 111979 */
            well_id: string;
            /** @example ypf */
            operator_slug: string;
            /** @example vaca_muerta */
            formation_slug: string;
            /** @example BAJO DEL TORO NORTE */
            concession: string;
            /** @example BAJO DEL TORO NORTE */
            yacimiento: string;
            /** @example NEUQUINA */
            basin: string;
            /** @example Neuquén */
            province: string;
            /** @example Petrolífero */
            well_type: string;
            /** @example Bombeo Mecánico */
            extraction_type: string;
            /** @example En Producción Efectiva */
            status_code: string;
            /** @example NO CONVENCIONAL */
            tipo_recurso: string;
            /** @example 2500 */
            depth_m: Record<string, never> | null;
            /** @example -69.36352 */
            coord_x: Record<string, never> | null;
            /** @example -37.40809 */
            coord_y: Record<string, never> | null;
            /** @example 12006.85 */
            oil_m3: number;
            /** @example 680.86 */
            gas_thousand_m3: number;
            /** @example 75520.9 */
            oil_bbl: number;
            /** @example 2517.3 */
            oil_bbl_d: number;
            /** @example 75520.9 */
            oil_boe: number;
            /** @example 0.02 */
            gas_mm3_d: number;
            /** @example 24044.34 */
            gas_mcf: number;
            /** @example 0.8 */
            gas_mmcf_d: number;
            /** @example 24838.3 */
            gas_boe: number;
            /** @example 100359.2 */
            boe: number;
            /** @example true */
            formation_vaca_muerta: boolean;
            /** @example true */
            unconventional: boolean;
            /** @example true */
            vm_combined: boolean;
        };
        VmShareDto: {
            /** @example 0.6848 */
            oil: number;
            /** @example 0.6649 */
            gas: number;
            /** @example 0.6678 */
            boe: number;
        };
        TopOperatorDto: {
            /** @example ypf */
            operator_slug: string;
            /** @example YPF S.A. */
            operator_name: string;
            /** @example 1757724.93 */
            oil_m3: number;
            /** @example 870517.38 */
            gas_thousand_m3: number;
            /** @example 42813011.69 */
            boe: number;
        };
        LatestSummaryDto: {
            /** @example 2026-04-01 */
            date_month: Record<string, never> | null;
            /** @example 3962125.07 */
            oil_m3: number;
            /** @example 830700.44 */
            oil_bbl_d: number;
            /** @example 4049482.51 */
            gas_thousand_m3: number;
            /** @example 4766.88 */
            gas_mmcf_d: number;
            /** @example 172649772.14 */
            boe: number;
            /** @example 22561 */
            active_wells: number;
            vm_share: components["schemas"]["VmShareDto"];
            top_operators: components["schemas"]["TopOperatorDto"][];
        };
        OperatorListItemDto: {
            /** @example ypf */
            operator_slug: string;
            /** @example YPF S.A. */
            operator_name: string;
            /** @example 2026-04-01 */
            latest_month: string;
            /** @example 1848981.5 */
            oil_m3: number;
            /** @example 387657.95 */
            oil_bbl_d: number;
            /** @example 888132.1 */
            gas_thousand_m3: number;
            /** @example 1045.49 */
            gas_mmcf_d: number;
            /** @example 44029598.96 */
            boe: number;
            /** @example 15290 */
            active_wells: number;
            /**
             * @description Share of total BOE in the latest month coming from Vaca Muerta wells.
             * @example 0.811
             */
            vm_share_boe: number;
        };
        OperatorLatestDto: {
            /** @example 1757724.93 */
            oil_m3: number;
            /** @example 368525.06 */
            oil_bbl_d: number;
            /** @example 870517.38 */
            gas_thousand_m3: number;
            /** @example 1024.74 */
            gas_mmcf_d: number;
            /** @example 42813011.69 */
            boe: number;
            /** @example 5044 */
            active_wells: number;
        };
        OperatorYtdDto: {
            /** @example 2026 */
            year: number;
            /** @example 7217666.24 */
            oil_m3: number;
            /** @example 45397749.4 */
            oil_bbl: number;
            /** @example 3520367.61 */
            gas_thousand_m3: number;
            /** @example 124320726.67 */
            gas_mcf: number;
            /** @example 173823921.59 */
            boe: number;
        };
        OperatorDetailDto: {
            /** @example ypf */
            operator_slug: string;
            /** @example YPF S.A. */
            operator_name: string;
            /**
             * @example [
             *       "YPF S.A."
             *     ]
             */
            aliases: string[];
            /** @example 2026-04-01 */
            latest_month: Record<string, never> | null;
            /** @example 1 */
            latest_month_rank: Record<string, never> | null;
            latest: components["schemas"]["OperatorLatestDto"] | null;
            ytd: components["schemas"]["OperatorYtdDto"];
        };
        ApiErrorPayloadDto: {
            /** @example NOT_FOUND */
            code: string;
            /** @example Well not found: 99999 */
            message: string;
        };
        ApiErrorDto: {
            error: components["schemas"]["ApiErrorPayloadDto"];
        };
        OperatorTimeSeriesPointDto: {
            /** @example 2026-01-01 */
            date_month: string;
            /** @example 1927666.93 */
            oil_m3: number;
            /** @example 404155.15 */
            oil_bbl_d: number;
            /** @example 836299.35 */
            gas_thousand_m3: number;
            /** @example 984.46 */
            gas_mmcf_d: number;
            /** @example 42633610.05 */
            boe: number;
            /** @example 5087 */
            active_wells: number;
        };
        WellDto: {
            /** @example 93863 */
            well_id: string;
            /** @example ACB.a-402 */
            sigla: string;
            /** @example ypf */
            operator_slug: string;
            /** @example YPF S.A. */
            operator_name: string;
            /** @example grupo_chubut */
            formation_slug: string;
            /** @example Chubut */
            province: string;
            /** @example GOLFO SAN JORGE */
            basin: string;
            /** @example MANANTIALES BEHR */
            concession: string;
            /** @example MANANTIALES BEHR */
            yacimiento: string;
            /** @example Petrolífero */
            well_type: string;
            /** @example Bombeo Mecánico */
            extraction_type: string;
            /** @example En Producción Efectiva */
            status_code: string;
            /** @example CONVENCIONAL */
            resource_type: string;
            /** @example No informado */
            sub_resource_type: string;
            /** @example 2300 */
            depth_m: Record<string, never> | null;
            /** @example -45.62363321 */
            latitude: Record<string, never> | null;
            /** @example -67.8618809 */
            longitude: Record<string, never> | null;
        };
        WellLatestProductionDto: {
            /** @example 2026-04-01 */
            date_month: string;
            /** @example 152.45 */
            oil_m3: number;
            /** @example 31.95 */
            oil_bbl_d: number;
            /** @example 84.32 */
            gas_thousand_m3: number;
            /** @example 0.099 */
            gas_mmcf_d: number;
            /** @example 1212.7 */
            boe: number;
            /** @example true */
            vm_combined: boolean;
        };
        WellDetailDto: {
            /** @example 93863 */
            well_id: string;
            /** @example ACB.a-402 */
            sigla: string;
            /** @example ypf */
            operator_slug: string;
            /** @example YPF S.A. */
            operator_name: string;
            /** @example grupo_chubut */
            formation_slug: string;
            /** @example Chubut */
            province: string;
            /** @example GOLFO SAN JORGE */
            basin: string;
            /** @example MANANTIALES BEHR */
            concession: string;
            /** @example MANANTIALES BEHR */
            yacimiento: string;
            /** @example Petrolífero */
            well_type: string;
            /** @example Bombeo Mecánico */
            extraction_type: string;
            /** @example En Producción Efectiva */
            status_code: string;
            /** @example CONVENCIONAL */
            resource_type: string;
            /** @example No informado */
            sub_resource_type: string;
            /** @example 2300 */
            depth_m: Record<string, never> | null;
            /** @example -45.62363321 */
            latitude: Record<string, never> | null;
            /** @example -67.8618809 */
            longitude: Record<string, never> | null;
            latest_production: components["schemas"]["WellLatestProductionDto"] | null;
        };
        WellTimeSeriesPointDto: {
            /** @example 2026-01-01 */
            date_month: string;
            /** @example 152.45 */
            oil_m3: number;
            /** @example 958.91 */
            oil_bbl: number;
            /** @example 31.95 */
            oil_bbl_d: number;
            /** @example 84.32 */
            gas_thousand_m3: number;
            /** @example 0.0028 */
            gas_mm3_d: number;
            /** @example 0.099 */
            gas_mmcf_d: number;
            /** @example 1212.7 */
            boe: number;
            /** @example true */
            vm_combined: boolean;
        };
        GeoPointGeometryDto: {
            /** @example Point */
            type: string;
            /**
             * @description [longitude, latitude] in WGS84, per GeoJSON spec.
             * @example [
             *       -69.36352,
             *       -37.40809
             *     ]
             */
            coordinates: number[];
        };
        GeoWellPropertiesDto: {
            /** @example 10000 */
            well_id: string;
            /** @example SJ.Nq.ET"E".x-1 */
            sigla: string;
            /** @example chevron */
            operator_slug: string;
            /** @example CHEVRON ARGENTINA S.R.L. */
            operator_name: string;
            /** @example huitr_n */
            formation_slug: string;
            /** @example NEUQUINA */
            basin: string;
            /** @example Neuquén */
            province: string;
            /** @example EL TRAPIAL ESTE */
            concession: string;
            /** @example EL TRAPIAL */
            yacimiento: string;
            /** @example Petrolífero */
            well_type: string;
            /** @example En Estudio */
            status_code: string;
            /** @example 1315 */
            depth_m: Record<string, never> | null;
        };
        GeoWellFeatureDto: {
            /** @example Feature */
            type: string;
            geometry: components["schemas"]["GeoPointGeometryDto"];
            properties: components["schemas"]["GeoWellPropertiesDto"];
        };
        GeoWellFeatureCollectionDto: {
            /** @example FeatureCollection */
            type: string;
            features: components["schemas"]["GeoWellFeatureDto"][];
        };
        TableRowCountDto: {
            /** @example 327686 */
            rows: number;
        };
        TableRowCountWithMonthDto: {
            /** @example 327686 */
            rows: number;
            /** @example 2026-04-01 */
            latest_month: Record<string, never> | null;
        };
        DataFreshnessTablesDto: {
            dim_operator: components["schemas"]["TableRowCountDto"];
            dim_formation: components["schemas"]["TableRowCountDto"];
            dim_well: components["schemas"]["TableRowCountDto"];
            fact_production_monthly: components["schemas"]["TableRowCountWithMonthDto"];
            agg_monthly_by_operator: components["schemas"]["TableRowCountWithMonthDto"];
        };
        DataFreshnessDto: {
            /** @example Secretaría de Energía / datos.energia.gob.ar */
            source: string;
            /** @example Producción de petróleo y gas por pozo */
            dataset: string;
            /** @example CC-BY-4.0 */
            license: string;
            /** @example 2026-04-01 */
            latest_month: Record<string, never> | null;
            /** @example 2026-01-01 */
            earliest_month: Record<string, never> | null;
            tables: components["schemas"]["DataFreshnessTablesDto"];
        };
        ProjectListItemDto: {
            /** @example Diablillos */
            project_name: string;
            /** @example Silver */
            primary_commodity: string;
            /** @example Gold, Lead, Zinc */
            by_products: Record<string, never> | null;
            /** @example Feasibility */
            status: Record<string, never> | null;
            /** @example High Sulphidation Epithermal Style */
            deposit_type: Record<string, never> | null;
            /** @example Salta */
            province: Record<string, never> | null;
            /** @example Argentina */
            country: Record<string, never> | null;
            /** @example -25.3 */
            latitude: Record<string, never> | null;
            /** @example -66.833 */
            longitude: Record<string, never> | null;
            /** @example AbraSilver Resource Corp. */
            operator: Record<string, never> | null;
            /**
             * @description Per-commodity headline numbers extracted from resources/reserves for at-a-glance comparison.
             * @example {
             *       "Silver": {
             *         "measured_kOz": 76684
             *       }
             *     }
             */
            commodity_highlights: {
                [key: string]: unknown;
            };
        };
        CommodityPriceDto: {
            /** @example SI=F */
            ticker: string;
            /** @example 74.83 */
            price: Record<string, never> | null;
            /** @example USD */
            currency: Record<string, never> | null;
            /** @example 74.55 */
            previous_close: Record<string, never> | null;
            /** @example 0.28 */
            change: Record<string, never> | null;
            /** @example 0.376 */
            change_pct: Record<string, never> | null;
            /** @example 121.3 */
            fifty_two_week_high: Record<string, never> | null;
            /** @example 32.66 */
            fifty_two_week_low: Record<string, never> | null;
            /** @example 2026-05-28T20:30:00.000Z */
            market_time: Record<string, never> | null;
            /** @example CMX */
            exchange: Record<string, never> | null;
            /** @example FUTURE */
            instrument_type: Record<string, never> | null;
            /** @example Silver May 26 */
            short_name: Record<string, never> | null;
            /** @example Silver */
            commodity: string;
            /** @example Silver futures (COMEX) */
            display: string;
            /** @example USD/oz */
            unit: string;
            /**
             * @description True when the ticker is a sector ETF proxy rather than a direct commodity feed.
             * @example false
             */
            proxy: boolean;
        };
        StockPriceDto: {
            /** @example SI=F */
            ticker: string;
            /** @example 74.83 */
            price: Record<string, never> | null;
            /** @example USD */
            currency: Record<string, never> | null;
            /** @example 74.55 */
            previous_close: Record<string, never> | null;
            /** @example 0.28 */
            change: Record<string, never> | null;
            /** @example 0.376 */
            change_pct: Record<string, never> | null;
            /** @example 121.3 */
            fifty_two_week_high: Record<string, never> | null;
            /** @example 32.66 */
            fifty_two_week_low: Record<string, never> | null;
            /** @example 2026-05-28T20:30:00.000Z */
            market_time: Record<string, never> | null;
            /** @example CMX */
            exchange: Record<string, never> | null;
            /** @example FUTURE */
            instrument_type: Record<string, never> | null;
            /** @example Silver May 26 */
            short_name: Record<string, never> | null;
            /** @example AbraSilver Resource Corp. */
            operator_match: string;
            /** @example OTC */
            exchange_label: string;
        };
        ProjectDetailDto: {
            /** @example Diablillos */
            project_name: string;
            /** @example Silver */
            primary_commodity: string;
            /** @example Gold, Lead, Zinc */
            by_products: Record<string, never> | null;
            /** @example Feasibility */
            status: Record<string, never> | null;
            /** @example High Sulphidation Epithermal Style */
            deposit_type: Record<string, never> | null;
            /** @example Salta */
            province: Record<string, never> | null;
            /** @example Argentina */
            country: Record<string, never> | null;
            /** @example -25.3 */
            latitude: Record<string, never> | null;
            /** @example -66.833 */
            longitude: Record<string, never> | null;
            /** @example AbraSilver Resource Corp. */
            operator: Record<string, never> | null;
            /**
             * @description Per-commodity headline numbers extracted from resources/reserves for at-a-glance comparison.
             * @example {
             *       "Silver": {
             *         "measured_kOz": 76684
             *       }
             *     }
             */
            commodity_highlights: {
                [key: string]: unknown;
            };
            /**
             * @example [
             *       "Gold",
             *       "Lead",
             *       "Zinc"
             *     ]
             */
            by_products_list: string[] | null;
            /** @example AbraSilver Resource Corp. */
            owner_controller: Record<string, never> | null;
            /** @example 7919 */
            area_ha: Record<string, never> | null;
            /**
             * @example {
             *       "since_production": 2029,
             *       "estimated_lom_years": 28,
             *       "productive_capacity": "9000 tpd",
             *       "estimated_annual_production": null,
             *       "capex": "620 M USD",
             *       "mining_method": "Open pit",
             *       "product": "Concentrate and doré"
             *     }
             */
            technical_economic: {
                [key: string]: unknown;
            } | null;
            /** @description Raw resources JSONB, as extracted by the pipeline. */
            resources: {
                [key: string]: unknown;
            } | null;
            /** @description Raw reserves JSONB, as extracted by the pipeline. */
            reserves: {
                [key: string]: unknown;
            } | null;
            /**
             * @description Reporting year of the resources/reserves table (when present in the source).
             * @example 2011
             */
            resources_year: Record<string, never> | null;
            /**
             * @description Free-text geology sections extracted from the deck.
             * @example {
             *       "regional": "The Laguna Salada Project is located near the western edge of the Cretaceous San Jorge Basin…",
             *       "deposit": "The mineralization at Laguna Salada is contained in flat-topped mesas…"
             *     }
             */
            geology: {
                [key: string]: string;
            } | null;
            /** @example silver_2026_pptx */
            source_pipeline: Record<string, never> | null;
            /** @example 2026-05-27T14:30:00.000Z */
            ingested_at: string;
            /** @description Live commodity prices for the project's primary commodity and any by-products we track. */
            commodity_prices: components["schemas"]["CommodityPriceDto"][];
            /** @description Live stock quote for the operator's parent company, if publicly traded and mapped. */
            stock: components["schemas"]["StockPriceDto"] | null;
        };
        CommodityRollupDto: {
            /** @example Silver */
            commodity: string;
            /** @example 12 */
            projects: number;
            /** @example 3 */
            producing_projects: number;
            /**
             * @description Sum of resource values across projects, keyed by category + unit (e.g. measured_kOz).
             * @example {
             *       "measured_kOz": 250000,
             *       "indicated_kOz": 400000
             *     }
             */
            resource_totals: {
                [key: string]: number;
            };
            /**
             * @description Sum of reserve values across projects.
             * @example {
             *       "proven_kOz": 50000,
             *       "probable_kOz": 100000
             *     }
             */
            reserve_totals: {
                [key: string]: number;
            };
        };
        SummaryDto: {
            /** @example 51 */
            total_projects: number;
            /**
             * @example {
             *       "Silver": 6,
             *       "Gold": 13,
             *       "Uranium": 4,
             *       "Copper": 8,
             *       "Lithium": 20
             *     }
             */
            by_commodity: {
                [key: string]: number;
            };
            /**
             * @example {
             *       "Operation": 8,
             *       "Feasibility": 6,
             *       "PEA": 10,
             *       "Exploration": 18
             *     }
             */
            by_status: {
                [key: string]: number;
            };
            /**
             * @example {
             *       "Salta": 10,
             *       "Jujuy": 8
             *     }
             */
            by_province: {
                [key: string]: number;
            };
            /**
             * @example [
             *       "silver_2026_pptx",
             *       "gold_2026_pptx",
             *       "uranium",
             *       "copper_2026_pptx",
             *       "lithium_2026_pptx"
             *     ]
             */
            data_sources: string[];
        };
        CommodityLatestDto: {
            /** @example gold */
            commodity: string;
            /** @example Gold */
            name: string;
            /** @example USD/troy oz */
            unit: string;
            /** @example 4569.9 */
            latest: Record<string, never> | null;
            /** @example 2026-05 */
            latest_date: Record<string, never> | null;
        };
        CommoditySeriesPointDto: {
            /** @example 2025-06 */
            date: string;
            /** @example 3890 */
            value: number;
        };
        EnergyLatestDto: {
            /** @example brent */
            series: string;
            /** @example Brent Crude */
            name: string;
            /** @example USD/bbl */
            unit: string;
            /** @example 78.5 */
            latest: Record<string, never> | null;
            /** @example 2026-04 */
            latest_date: Record<string, never> | null;
        };
        FuelPriceRowDto: {
            /** @example NEUQUEN */
            provincia: string;
            /** @example NEUQUEN */
            localidad: Record<string, never> | null;
            /** @example Nafta Premium */
            producto: string;
            /** @example YPF */
            empresa_bandera: Record<string, never> | null;
            /** @example 10 DE SETIEMBRE S.A. */
            empresa: Record<string, never> | null;
            /** @example 1250 */
            precio: number;
            /** @example 2026-05-01 */
            fecha_vigencia: string;
            /** @example Diurno */
            tipo_horario: Record<string, never> | null;
            /** @example -38.95 */
            latitude: Record<string, never> | null;
            /** @example -68.06 */
            longitude: Record<string, never> | null;
        };
        FuelLatestEntryDto: {
            /** @example NEUQUEN */
            provincia: string;
            /** @example Nafta Premium */
            producto: string;
            /** @example 1250 */
            precio_promedio: number;
            /** @example 1190 */
            precio_min: number;
            /** @example 1310 */
            precio_max: number;
            /** @example 142 */
            sample_size: number;
            /** @example 2026-05-29 */
            fecha_vigencia: string;
        };
        FxPointDto: {
            /** @example 2026-05-29 */
            date: string;
            /** @example 1432 */
            oficial_sell: Record<string, never> | null;
            /** @example 1380 */
            oficial_buy: Record<string, never> | null;
            /** @example 1430 */
            blue_sell: Record<string, never> | null;
            /** @example 1410 */
            blue_buy: Record<string, never> | null;
        };
        FxLatestDto: {
            /** @example 2026-05-29 */
            date: string;
            /** @example 1432 */
            oficial_sell: Record<string, never> | null;
            /** @example 1380 */
            oficial_buy: Record<string, never> | null;
            /** @example 1430 */
            blue_sell: Record<string, never> | null;
            /** @example 1410 */
            blue_buy: Record<string, never> | null;
        };
        RigCountPointDto: {
            /** @example 2026-04 */
            date: string;
            /** @example 71 */
            oil_rigs: Record<string, never> | null;
            /** @example 14 */
            gas_rigs: Record<string, never> | null;
            /** @example 85 */
            total_rigs: Record<string, never> | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_health_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDto"];
                };
            };
        };
    };
    ProductionController_monthly_v1: {
        parameters: {
            query?: {
                /** @description Filter by operator slug (see /operators for valid values). */
                operator?: string;
                /** @description Filter by formation slug. */
                formation?: string;
                /** @description Filter by province name (matches CSV exactly, e.g. "Neuquén"). */
                province?: string;
                /** @description Restrict to Vaca Muerta production (`vm_combined` = formation + unconventional + sub-tipo). Use "true" or "false". */
                vm?: "true" | "false";
                /** @description Inclusive lower bound for `date_month` (YYYY-MM or YYYY-MM-DD). */
                from?: string;
                /** @description Inclusive upper bound for `date_month` (YYYY-MM or YYYY-MM-DD). */
                to?: string;
                /** @description Aggregate on the fly instead of returning per-well rows. The grouped result includes oil/gas totals, BOE, and `active_wells`. */
                group_by?: "operator" | "concession" | "formation" | "province";
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default (ungrouped) response. When `group_by` is supplied, items follow `GroupedProductionRowDto` instead. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProductionFactDto"][];
                        meta: components["schemas"]["MetaDto"];
                        pagination: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
        };
    };
    ProductionController_latest_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LatestSummaryDto"];
                        meta: components["schemas"]["MetaDto"];
                    };
                };
            };
        };
    };
    OperatorsController_list_v1: {
        parameters: {
            query?: {
                /** @description Sort key for the latest-month totals. */
                sort?: "oil_m3" | "gas_thousand_m3" | "boe" | "active_wells";
                order?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OperatorListItemDto"][];
                        meta: components["schemas"]["MetaDto"];
                    };
                };
            };
        };
    };
    OperatorsController_detail_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OperatorDetailDto"];
                        meta: components["schemas"]["MetaDto"];
                    };
                };
            };
            /** @description Operator slug not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    OperatorsController_production_v1: {
        parameters: {
            query?: {
                /** @description Inclusive lower bound (YYYY-MM or YYYY-MM-DD). */
                from?: string;
                /** @description Inclusive upper bound (YYYY-MM or YYYY-MM-DD). */
                to?: string;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OperatorTimeSeriesPointDto"][];
                        meta: components["schemas"]["MetaDto"];
                    };
                };
            };
            /** @description Operator slug not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    WellsController_list_v1: {
        parameters: {
            query?: {
                /** @description Filter by operator slug. */
                operator?: string;
                /** @description Filter by formation slug. */
                formation?: string;
                /** @description Filter by basin (matches CSV exactly). */
                basin?: string;
                /** @description Filter by province. */
                province?: string;
                /** @description Filter by concession (matches CSV exactly). */
                concession?: string;
                /** @description Case-insensitive substring search on `sigla` (well name). */
                search?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["WellDto"][];
                        meta: components["schemas"]["MetaDto"];
                        pagination: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
        };
    };
    WellsController_detail_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Internal `well_id` (numeric string). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["WellDetailDto"];
                        meta: components["schemas"]["MetaDto"];
                    };
                };
            };
            /** @description Well ID not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    WellsController_production_v1: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["WellTimeSeriesPointDto"][];
                        meta: components["schemas"]["MetaDto"];
                    };
                };
            };
            /** @description Well ID not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    GeoController_wells_v1: {
        parameters: {
            query?: {
                operator?: string;
                formation?: string;
                basin?: string;
                province?: string;
                /** @description Bounding box `west,south,east,north` in WGS84 decimal degrees. Use for viewport-based loading. */
                bbox?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GeoJSON FeatureCollection of well points. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoWellFeatureCollectionDto"];
                };
            };
            /** @description Invalid bbox format. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    GeoController_well_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GeoJSON Feature for one well. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoWellFeatureDto"];
                };
            };
            /** @description Well missing or has no geometry. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    DataStatusController_freshness_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DataFreshnessDto"];
                        meta: components["schemas"]["MetaDto"];
                    };
                };
            };
        };
    };
    MineralsController_list_v2: {
        parameters: {
            query?: {
                /** @description Filter by primary commodity (case-insensitive exact match). */
                commodity?: string;
                /** @description Filter by project status (case-insensitive exact match). */
                status?: string;
                /** @description Filter by province (case-insensitive exact match). */
                province?: string;
                /** @description Case-insensitive substring search across project_name, operator, province. */
                q?: string;
                sort?: "project_name" | "primary_commodity" | "status" | "province";
                order?: "asc" | "desc";
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProjectListItemDto"][];
                        meta: components["schemas"]["MetaDto"];
                        pagination: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
        };
    };
    MineralsController_detail_v2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name (case-sensitive, as ingested). */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProjectDetailDto"];
                        meta: components["schemas"]["MetaDto"];
                    };
                };
            };
            /** @description Project name not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    MineralsController_commodities_v2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CommodityRollupDto"][];
                        meta: components["schemas"]["MetaDto"];
                    };
                };
            };
        };
    };
    MineralsController_commodityProjects_v2: {
        parameters: {
            query?: {
                status?: string;
                province?: string;
                /** @description If true, only include projects that have at least one resource entry. */
                min_resources?: boolean;
            };
            header?: never;
            path: {
                commodity: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects grouped under one commodity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MineralsController_map_v2: {
        parameters: {
            query?: {
                commodity?: string;
                status?: string;
                province?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GeoJSON FeatureCollection of project points. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MineralsController_summary_v2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SummaryDto"];
                        meta: components["schemas"]["MetaDto"];
                    };
                };
            };
        };
    };
    MineralsController_prices_v2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CommodityPriceDto"][];
                        meta: components["schemas"]["MetaDto"];
                    };
                };
            };
        };
    };
    MineralsController_price_v2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commodity: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CommodityPriceDto"];
                        meta: components["schemas"]["MetaDto"];
                    };
                };
            };
            /** @description Commodity not tracked. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    PricesController_commodities_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CommodityLatestDto"][];
                        meta: components["schemas"]["MetaDto"];
                    };
                };
            };
        };
    };
    PricesController_commoditySeries_v1: {
        parameters: {
            query?: {
                /** @description Inclusive start (YYYY-MM or YYYY-MM-DD). */
                from?: string;
                to?: string;
            };
            header?: never;
            path: {
                commodity: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CommoditySeriesPointDto"][];
                        meta: components["schemas"]["MetaDto"];
                    };
                };
            };
            /** @description Series not tracked. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    PricesController_energy_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["EnergyLatestDto"][];
                        meta: components["schemas"]["MetaDto"];
                    };
                };
            };
        };
    };
    PricesController_fuel_v1: {
        parameters: {
            query?: {
                /** @description Province name (case-insensitive exact match). */
                provincia?: string;
                /** @description Product label (case-insensitive exact match). */
                producto?: string;
                /** @description Bandera (brand) — case-insensitive exact match. */
                bandera?: string;
                /** @description Inclusive lower bound on fecha_vigencia. */
                from?: string;
                to?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FuelPriceRowDto"][];
                        meta: components["schemas"]["MetaDto"];
                        pagination: components["schemas"]["PaginationMetaDto"];
                    };
                };
            };
        };
    };
    PricesController_fuelLatest_v1: {
        parameters: {
            query?: {
                provincia?: string;
                producto?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FuelLatestEntryDto"][];
                        meta: components["schemas"]["MetaDto"];
                    };
                };
            };
        };
    };
    MacroController_fxSeries_v1: {
        parameters: {
            query?: {
                /** @description Inclusive start (YYYY-MM-DD). */
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FxPointDto"][];
                        meta: components["schemas"]["MetaDto"];
                    };
                };
            };
        };
    };
    MacroController_fxLatest_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FxLatestDto"];
                        meta: components["schemas"]["MetaDto"];
                    };
                };
            };
            /** @description No FX data ingested. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
    MacroController_rigCount_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RigCountPointDto"][];
                        meta: components["schemas"]["MetaDto"];
                    };
                };
            };
        };
    };
    MacroController_rigCountLatest_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RigCountPointDto"];
                        meta: components["schemas"]["MetaDto"];
                    };
                };
            };
            /** @description No rig-count data ingested. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorDto"];
                };
            };
        };
    };
}
