// AUTO-GENERATED by scripts/build-pipelines.py — do not edit by hand.
// Aggregates of Argentina's trunk pipeline network (km by transport
// operator + totals), derived from the official Secretaría de Energía /
// ENARGAS open datasets. Regenerate when the upstream data refreshes.

export interface PipelineOperatorKm {
  operator: string
  km: number
}

export interface PipelineStats {
  totalKm: number
  gasKm: number
  oilKm: number
  gasSegments: number
  oilSegments: number
  operators: PipelineOperatorKm[]
  source: { label: string; url: string; asOf: string }
}

export const PIPELINE_STATS: PipelineStats = {
  "totalKm": 30712,
  "gasKm": 19413,
  "oilKm": 11299,
  "gasSegments": 296,
  "oilSegments": 393,
  "operators": [
    {
      "operator": "TGS",
      "km": 9734
    },
    {
      "operator": "TGN",
      "km": 7230
    },
    {
      "operator": "Atacama",
      "km": 530
    },
    {
      "operator": "Nor Andino",
      "km": 375
    },
    {
      "operator": "GasAndes",
      "km": 313
    },
    {
      "operator": "Gas del Pacífico",
      "km": 297
    },
    {
      "operator": "TGS / TGN",
      "km": 80
    }
  ],
  "source": {
    "label": "Secretaría de Energía · ENARGAS",
    "url": "https://datos.energia.gob.ar/dataset/transporte-hidrocarburos-ductos-troncales-gasoductos",
    "asOf": "2024"
  }
}
