export const CHAIN_OPTIONS = [
  { label: 'Ethereum', value: 'ethereum' },
  { label: 'Polygon', value: 'polygon' },
  { label: 'Arbitrum', value: 'arbitrum' },
  { label: 'Optimism', value: 'optimism' },
  { label: 'Base', value: 'base' },
  { label: 'BSC', value: 'bsc' },
  { label: 'Avalanche', value: 'avalanche' },
  { label: 'Solana', value: 'solana' },
  { label: 'Tron', value: 'tron' },
  { label: 'Stellar', value: 'stellar' },
  { label: 'Gnosis', value: 'gnosis' },
  { label: 'Celo', value: 'celo' },
  { label: 'ZKsync Era', value: 'zksync' },
  { label: 'Linea', value: 'linea' },
  { label: 'Scroll', value: 'scroll' },
  { label: 'Moonbeam', value: 'moonbeam' },
  { label: 'Mantle', value: 'mantle' },
  { label: 'Rootstock', value: 'rootstock' },
  { label: 'Sonic', value: 'sonic' },
  { label: 'Cardano', value: 'cardano' },
  { label: 'Hedera', value: 'hedera' },
  { label: 'XRPL', value: 'xrpl' },
  { label: 'XDC', value: 'xdc' },
  { label: 'Algorand', value: 'algorand' },
  { label: 'ICP', value: 'icp' },
  { label: 'World Chain', value: 'worldchain' },
  { label: 'Other', value: 'other' },
] as const

export const NETWORK_OPTIONS = CHAIN_OPTIONS
